# Generated by Django 4.2.6 on 2023-11-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nirn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nirnroot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('passphrase', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NirnFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='nirn_files/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nirn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nirn.nirn')),
            ],
        ),
        migrations.AddField(
            model_name='nirn',
            name='nirnroot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nirn.nirnroot'),
        ),
    ]
